// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAQiQh1vCzP7KB0Ex-BJKOAwpqDvsNK0c',
    appId: '1:614466088796:web:7dd330463776fd863c1b99',
    messagingSenderId: '614466088796',
    projectId: 'travelbook-28999',
    authDomain: 'travelbook-28999.firebaseapp.com',
    storageBucket: 'travelbook-28999.firebasestorage.app',
    measurementId: 'G-KYL5T0699C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzXS-m2b2ib51RNzGiwPC6ley6YWYT3F4',
    appId: '1:614466088796:android:a45af61bb93b9d683c1b99',
    messagingSenderId: '614466088796',
    projectId: 'travelbook-28999',
    storageBucket: 'travelbook-28999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2uPVqNxu-Khzd8l9Q-i8rlhH8050csn4',
    appId: '1:614466088796:ios:fc499bc4574330b83c1b99',
    messagingSenderId: '614466088796',
    projectId: 'travelbook-28999',
    storageBucket: 'travelbook-28999.firebasestorage.app',
    iosBundleId: 'com.example.travelbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2uPVqNxu-Khzd8l9Q-i8rlhH8050csn4',
    appId: '1:614466088796:ios:fc499bc4574330b83c1b99',
    messagingSenderId: '614466088796',
    projectId: 'travelbook-28999',
    storageBucket: 'travelbook-28999.firebasestorage.app',
    iosBundleId: 'com.example.travelbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAQiQh1vCzP7KB0Ex-BJKOAwpqDvsNK0c',
    appId: '1:614466088796:web:a910db86a8236f5e3c1b99',
    messagingSenderId: '614466088796',
    projectId: 'travelbook-28999',
    authDomain: 'travelbook-28999.firebaseapp.com',
    storageBucket: 'travelbook-28999.firebasestorage.app',
    measurementId: 'G-K2XY2JKZLJ',
  );
}
